version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_trader
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build: .
    container_name: trader_backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongo:27017/trader_alerting
      SPRING_PROFILES_ACTIVE: docker
