version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_trader
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build: .
    container_name: trader_backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mongo
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/trader_db"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

      SERVER_PORT: ${SERVER_PORT}
